experiment: 
  type: experiment/online_learning
  runs: 1
  trials: 0
  steps: 0
  rate: 0
  test_interval: 10
  environment: 
    type: environment/modeled
    model: 
      type: model/dynamical
      control_step: 0.03
      integration_steps: 5
      dynamics: 
        type: dynamics/pendulum
    task: 
      type: task/pendulum/swingup
      timeout: 2.99
      randomization: 0
  agent: 
    type: agent/replay
    replay_steps: 64
    batch_size: 64
    threads: 0
    policy: 
      type: mapping/policy/discrete/value/q
      discretizer:
        type: discretizer/uniform
        min: experiment/environment/task/action_min
        max: experiment/environment/task/action_max
        steps: [3]
      projector:
        type: projector/pre/normalizing
        input_min: experiment/environment/task/observation_min++experiment/environment/task/action_min
        input_max: experiment/environment/task/observation_max++experiment/environment/task/action_max
        projector: 
          type: projector/identity
      representation:
        type: representation/parameterized/ann
        inputs: experiment/environment/task/observation_dims+experiment/environment/task/action_dims
        outputs: 1
        hiddens: 100
        eta: -0.001
        interval: 1000
      sampler: 
        type: sampler/epsilon_greedy
        epsilon: 0.5
    predictor: 
      type: predictor/critic/q
      alpha: 0.2
      gamma: 0.97
      lambda: 0.65
      discretizer: experiment/agent/policy/discretizer
      projector: experiment/agent/policy/projector
      representation: experiment/agent/policy/representation
      target_representation: experiment/agent/policy/representation/target
  test_agent: 
    type: agent/fixed
    policy: 
      type: mapping/policy/discrete/value/q
      discretizer: experiment/agent/policy/discretizer
      projector: experiment/agent/policy/projector
      representation: experiment/agent/policy/representation
      sampler: 
        type: sampler/greedy
  save_every: never
visualizer: 
  type: visualizer/glut
policy_visualization: 
  type: visualization/field/mapping
  field_dims: [0, 1]
  input_min: experiment/environment/task/observation_min
  input_max: experiment/environment/task/observation_max
  points: 65536
  savepoints: 1048576
  state: experiment/state
  projection: mean
  mapping: experiment/test_agent/policy
  output_dim: 0
value_visualization: 
  type: visualization/field/policy/value
  field_dims: [0, 1]
  input_min: experiment/environment/task/observation_min
  input_max: experiment/environment/task/observation_max
  points: 65536
  savepoints: 1048576
  projection: mean
  policy: experiment/test_agent/policy
target_visualization: 
  type: visualization/field/policy/value
  field_dims: [0, 1]
  input_min: experiment/environment/task/observation_min
  input_max: experiment/environment/task/observation_max
  points: 65536
  savepoints: 1048576
  projection: mean
  policy:
    type: mapping/policy/discrete/value/q
    discretizer: experiment/test_agent/policy/discretizer
    projector: experiment/test_agent/policy/projector
    representation: experiment/test_agent/policy/representation/target
    sampler: 
      type: sampler/greedy
