experiment: 
  type: experiment/online_learning
  runs: 10
  run_offset: 0
  trials: 1000
  steps: 0
  rate: 0
  test_interval: 10
  output: ddpg_test
  environment: 
    type: environment/modeled
    model: 
      type: model/dynamical
      control_step: 0.03
      integration_steps: 5
      dynamics: 
        type: dynamics/pendulum
    task: 
      type: task/pendulum/swingup
      timeout: 2.99
      randomization: 0
  agent: 
    type: agent/replay
    replay_steps: 64
    batch_size: 16
    observation_steps: 1000
    threads: 0
    policy: 
      type: mapping/policy/filtering
      observation_idx: [0, 1]
      action_idx: [1]
      policy: 
        type: mapping/policy/action
        sigma: [1]
        theta: [0.15]
        renormalize: 1
        output_min: 0++experiment/environment/task/action_min
        output_max: 0++experiment/environment/task/action_max
        projector: 
          type: projector/pre/normalizing
          input_min: experiment/environment/task/observation_min
          input_max: experiment/environment/task/observation_max
          projector: 
            type: projector/pre/geometric
            angles: [1, 0]
            normalized: 1
            projector:
              type: projector/identity
        representation: 
          type: representation/parameterized/tensorflow
          interval: 100
          tau: 0.01
          file: $@/4layer_tanh_ddpg.py ../../projector/projector/memory experiment/environment/task/action_dims
          input_layer: s_in, a_in
          output_layer: q/BiasAdd, a_out/Tanh
    predictor: 
      type: predictor/ddpg
      gamma: 0.99
      reward_scale: 0.1
      observation: s_in
      action: a_in
      value: q/BiasAdd
      target: target
      critic_update: update
      actor_update: a_update
      obs_projector: ../../policy/policy/projector
      action_projector: 
        type: projector/pre/normalizing
        signed: 1
        input_min: experiment/environment/task/action_min
        input_max: experiment/environment/task/action_max
        projector: 
          type: projector/identity
      representation: experiment/agent/policy/policy/representation
  test_agent: 
    type: agent/fixed
    policy: 
      type: mapping/policy/filtering
      observation_idx: [0, 1]
      action_idx: [1]
      policy: 
        type: mapping/policy/action
        renormalize: 1
        output_min: experiment/agent/policy/policy/output_min
        output_max: experiment/agent/policy/policy/output_max
        projector: experiment/agent/policy/policy/projector
        representation: experiment/agent/policy/policy/representation
  save_every: never
visualizer: 
  type: visualizer/glut
points: 4096
delay: 1
policy_visualization: 
  type: visualization/slice
  field_dims: [0, 1]
  input_min: experiment/environment/task/observation_min
  input_max: experiment/environment/task/observation_max
  operating_point: []
  output_dim: 1
  points: /points
  delay: /delay
  state: experiment/state
  mapping: experiment/test_agent/policy/policy
value_visualization: 
  type: visualization/slice
  field_dims: [0, 1]
  input_min: experiment/environment/task/observation_min
  input_max: experiment/environment/task/observation_max
  operating_point: []
  output_dim: 0
  points: /points
  delay: /delay
  state: experiment/state
  mapping: 
    type: mapping/represented
    projector: experiment/agent/policy/policy/projector
    representation: experiment/agent/policy/policy/representation
target_value_visualization: 
  type: visualization/slice
  field_dims: [0, 1]
  input_min: experiment/environment/task/observation_min
  input_max: experiment/environment/task/observation_max
  operating_point: []
  output_dim: 0
  points: /points
  delay: /delay
  state: experiment/state
  mapping: 
    type: mapping/represented
    projector: experiment/agent/policy/policy/projector
    representation: experiment/agent/policy/policy/representation/target
curve_visualization: 
  type: visualization/state
  input_dims: []
  input_min: [-4000]
  input_max: [0]
  memory: 256
  state: experiment/curve
