experiment: 
  type: experiment/online_learning
  runs: 1
  run_offset: 0
  trials: 0
  steps: 0
  rate: 0
  test_interval: 10
  environment: 
    type: environment/modeled
    model: 
      type: model/dynamical
      control_step: 0.03
      integration_steps: 5
      dynamics: 
        type: dynamics/integrator
        order: 2
    task: 
      type: task/integrator/regulator
      order: experiment/environment/model/dynamics/order
      start: [ 1, 0 ]
      goal: [ 0, 0 ]
      stddev: [ 1, 0 ]
      q: [ 1, 0 ]
      r: [ 0.01 ]
      function: quadratic
      r_function: quadratic
      smoothing: 0.01
  agent: 
    type: agent/replay
    replay_steps: 64
    batch_size: 64
    threads: 0
    policy: 
      type: mapping/policy/filtering
      observation_idx: [0, 1]
      action_idx: [0]
      policy: 
        type: mapping/policy/action
        sigma: 1
        decay_rate: 0
        decay_min: 0
        output_min: experiment/environment/task/action_min++[0]
        output_max: experiment/environment/task/action_max++[0]
        projector: 
          type: projector/pre/normalizing
          input_min: experiment/environment/task/observation_min
          input_max: experiment/environment/task/observation_max
          projector: 
            type: projector/identity
        representation: 
          type: representation/parameterized/tensorflow
          interval: 10000
          file: $@/../4layer_tanh_ddpg.py experiment/environment/task/observation_dims experiment/environment/task/action_dims
          input_layer: s_in, a_in
          output_layer: a_out/Tanh, q/BiasAdd
    predictor: 
      type: predictor/ddpg
      gamma: 0.9
      observation: s_in
      action_in: a_in
      action_out: a_out/Tanh
      value: q/BiasAdd
      target: target
      critic_update: update
      actor_update: a_update
      obs_projector: 
        type: projector/pre/normalizing
        input_min: experiment/environment/task/observation_min
        input_max: experiment/environment/task/observation_max
        projector: 
          type: projector/identity
      action_projector: 
        type: projector/identity
      representation: experiment/agent/policy/policy/representation
  test_agent: 
    type: agent/fixed
    policy: 
      type: mapping/policy/filtering
      observation_idx: [0, 1]
      action_idx: [0]
      policy: 
        type: mapping/policy/action
        sigma: 0
        decay_rate: 1
        decay_min: 0
        output_min: experiment/agent/policy/policy/output_min
        output_max: experiment/agent/policy/policy/output_max
        projector: experiment/agent/policy/policy/projector
        representation: experiment/agent/policy/policy/representation
  save_every: never
visualizer: 
  type: visualizer/glut
policy_visualization: 
  type: visualization/slice
  field_dims: [0, 1]
  input_min: experiment/environment/task/observation_min
  input_max: experiment/environment/task/observation_max
  operating_point: []
  output_dim: 0
  points: 65536
  state: experiment/state
  mapping: 
    type: mapping/filtering
    input_idx: [0, 1]
    output_idx: [0]
    mapping: 
      type: mapping/represented
      projector: experiment/agent/policy/policy/projector
      representation: experiment/agent/policy/policy/representation
value_visualization: 
  type: visualization/slice
  field_dims: [0, 1]
  input_min: experiment/environment/task/observation_min
  input_max: experiment/environment/task/observation_max
  operating_point: []
  output_dim: 0
  points: 65536
  state: experiment/state
  mapping: 
    type: mapping/filtering
    input_idx: [0, 1]
    output_idx: [1]
    mapping: 
      type: mapping/represented
      projector: experiment/agent/policy/policy/projector
      representation: experiment/agent/policy/policy/representation
target_value_visualization: 
  type: visualization/slice
  field_dims: [0, 1]
  input_min: experiment/environment/task/observation_min
  input_max: experiment/environment/task/observation_max
  operating_point: []
  output_dim: 0
  points: 65536
  state: experiment/state
  mapping: 
    type: mapping/filtering
    input_idx: [0, 1]
    output_idx: [1]
    mapping: 
      type: mapping/represented
      projector: experiment/agent/policy/policy/projector
      representation: experiment/agent/policy/policy/representation/target
curve_visualization: 
  type: visualization/state
  input_dims: []
  input_min: [-100]
  input_max: [0]
  memory: 256
  state: experiment/curve
